import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// src/components/TopDeals.tsx
import { useState } from "react";
import { topDeals } from "../data/mockData";
import { ChevronRight } from "lucide-react";
const TopDeals = () => {
    const [activeTab, setActiveTab] = useState("Bangkok");
    const tabs = Object.keys(topDeals);
    return (_jsx("section", { className: "py-16 bg-white", children: _jsxs("div", { className: "container mx-auto px-4", children: [_jsxs("div", { className: "flex justify-between items-center mb-10", children: [_jsx("h2", { className: "text-2xl md:text-4xl font-bold text-gray-900", children: "Our Top deals for today" }), _jsxs("button", { className: "text-cyan-600 font-semibold text-sm hover:text-cyan-700 transition flex items-center gap-2 group", children: ["View all", _jsx(ChevronRight, { className: "w-5 h-5 group-hover:translate-x-1 transition" })] })] }), _jsx("div", { className: "flex flex-wrap gap-4 md:gap-4 mb-8", children: tabs.map((tab) => (_jsx("button", { onClick: () => setActiveTab(tab), className: `px-6 py-2 rounded-lg font-medium transition-all duration-300 ${activeTab === tab
                            ? "bg-cyan-400 text-white shadow-md"
                            : "bg-gray-100 text-gray-600 hover:bg-gray-200"}`, children: tab }, tab))) }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6", children: topDeals[activeTab]?.map((deal) => (_jsxs("div", { className: "bg-white rounded-xl overflow-hidden shadow-lg hover:shadow-2xl transition-all duration-300 cursor-pointer group", children: [_jsxs("div", { className: "relative h-48 overflow-hidden", children: [_jsx("img", { src: deal.image, alt: deal.name, className: "w-full h-full object-cover group-hover:scale-110 transition-transform duration-500" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-black/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" })] }), _jsxs("div", { className: "p-4", children: [_jsxs("h3", { className: "text-lg font-bold mb-2 text-gray-900 group-hover:text-cyan-600 transition", children: [deal.name, ", ", deal.country] }), _jsxs("div", { className: "flex items-center gap-2 mb-3", children: [_jsxs("span", { className: "bg-green-100 text-green-700 px-2 py-1 rounded text-sm font-semibold", children: [deal.rating, "/5"] }), _jsxs("span", { className: "text-gray-500 text-sm", children: ["(", deal.reviews, " Reviews)"] })] }), _jsx("p", { className: "text-sm text-gray-600 mb-1", children: deal.perNight ? "Per Night" : "Total Price" }), _jsxs("p", { className: "text-xl font-bold text-gray-900", children: ["GHS ", deal.price.toLocaleString()] })] })] }, deal.id))) })] }) }));
};
export default TopDeals;
